## Imports

In [1]:
import pandas as pd
import numpy as np

## Step 1: Load Data

In [2]:
data = pd.read_csv("Real estate.csv")

In [3]:
data.shape

(414, 8)

In [4]:
data.head()

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   No                                      414 non-null    int64
 1   X1 transaction date                     414 non-null    float64
 2   X2 house age                            414 non-null    float64
 3   X3 distance to the nearest MRT station  414 non-null    float64
 4   X4 number of convenience stores         414 non-null    int64
 5   X5 latitude                             414 non-null    float64
 6   X6 longitude                            414 non-null    float64
 7   Y house price of unit area              414 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 26.0 KB

In [6]:
data.set_index("No", inplace=True)

In [7]:
data.head()

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
No,,,,,,,
1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1

In [8]:
data["X1 transaction date"] = data["X1 transaction date"].astype(int)

In [9]:
data.head()

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
No,,,,,,,
1,2012,32.0,84.87882,10,24.98298,121.54024,37.9
2,2012,19.5,306.59470,9,24.98034,121.53951,42.2
3,2013,13.3,561.98450,5,24.98746,121.54391,47.3
4,2013,13.3,561.98450,5,24.98746,121.54391,54.8
5,2012,5.0,390.56840,5,24.97937,121.54245,43.1

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 414 entries, 1 to 414
Data columns (total 7 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   X1 transaction date                     414 non-null    int32
 1   X2 house age                            414 non-null    float64
 2   X3 distance to the nearest MRT station  414 non-null    float64
 3   X4 number of convenience stores         414 non-null    int64
 4   X5 latitude                             414 non-null    float64
 5   X6 longitude                            414 non-null    float64
 6   Y house price of unit area              414 non-null    float64
dtypes: float64(5), int32(1), int64(1)
memory usage: 24.3 KB

In [11]:
data.shape

(414, 7)

In [13]:
data.duplicated().sum()

0

In [14]:
data.isna().sum()

X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

## Step 3: Separate Input Output Feature

In [15]:
data.columns

Index(['X1 transaction date', 'X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude',
       'Y house price of unit area'],
      dtype='object')

In [16]:
X = data.drop('Y house price of unit area', axis=1)
y = data['Y house price of unit area']

In [17]:
X

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude
No,,,,,,
1,2012,32.0,84.87882,10,24.98298,121.54024
2,2012,19.5,306.59470,9,24.98034,121.53951
3,2013,13.3,561.98450,5,24.98746,121.54391
4,2013,13.3,561.98450,5,24.98746,121.54391
5,2012,5.0,390.56840,5,24.97937,121.54245
...,...,...,...,...,...,...
410,2013,13.7,4082.01500,0,24.94155,121.50381
411,2012,5.6,90.45606,9,24.97433,121.54310
412,2013,18.8,390.96960,7,24.97923,121.53986
413,2013,8.1,104.81010,5,24.96674,121.54067
414,2013,6.5,90.45606,9,24.97433,121.54310

In [18]:
y

No
1      37.9
2      42.2
3      47.3
4      54.8
5      43.1
       ...
410    15.4
411    50.0
412    40.6
413    52.5
414    63.9
Name: Y house price of unit area, Length: 414, dtype: float64

## Split Train and Test

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size=0.2)

## Model Selection

In [20]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [21]:
lr.fit(X_train,y_train)

LinearRegression()

In [22]:
lr.coef_

array([ 2.68705389e+00, -2.66936871e-01, -4.33085173e-03,  1.12694349e+00,
        2.33077479e+02, -1.02057128e+01])

In [23]:
lr.intercept_

-9944.793708413306

## Predict on Training Data

In [24]:
y_pred_train = lr.predict(X_train)

In [25]:
y_pred_train

array([30.52614728, 34.80307055, 32.09423117, 41.33667785, 44.81333157,
       53.62403958, 48.40875175, 40.63906324, 42.98523972, 31.4691486 ,
       33.0909576 , 22.97761903, 40.38177493, 33.96855515, 43.08537084,
       15.73831483, 45.16895039, 40.63906324, 40.03021131, 40.71573158,
       44.0185957 , 41.66792924, 28.99564421, 42.81273056,  8.70679258,
       43.25995913, 16.1640525 , 46.7937805 , 43.34100124, 32.65201584,
       42.58427411, 49.00797574, 37.41607115, 46.25054545, 41.05792095,
       38.15794645, 31.51777075, 35.41782885, 39.3600613 , 31.49584229,
       43.96520833, 50.33451964, 44.27275697, 52.80802404, 48.85939217,
       15.76668104, 44.26443038, 40.03763031, 54.67298861, 50.25443858,
       27.63667244, 34.55581626, 15.2081526 , 40.41560623, 40.05738234,
       50.64224186, 48.43544543, 42.66387783, 37.09886352, 46.61381613,
       39.06948838, 43.85495508, 38.37906779, 50.42242489, 37.34156757,
       40.63906324, 49.28837248, 42.55710308, 12.68359408, 44.00292881,
        8.76017996, 43.75498144, 39.3810655 , 45.45084226, 16.19074619,
        3.47133309, 44.3134164 , 42.63718414, 28.28208084, 33.45174872,
       11.74637536, 44.16011398, 38.63070975, 36.51367672, 33.11765129,
       41.29055362, 43.30129773, 47.55532768, 46.6750969 , 30.41742944,
       13.29150412, 47.27197085, 25.67922758, 38.72416449, 49.39073692,
       49.32127791, 44.79630333, 38.57454917, 37.57093249, 46.56042875,
       38.0635714 , 31.49253343, 13.05678575, 35.74493411, 37.83958399,
       46.15188307, 31.76049968, 47.17438355, 45.98557997, 16.1640525 ,
       44.33225268, 15.35169922, 39.09727381, 48.40875175, 46.81468683,
       52.29097503, 46.24411484, 30.91555514, 25.08910101, 40.09101768,
       29.57381903, 42.17888581, 47.46830657, 34.51542306, 25.28827407,
       29.54790525, 40.76380908, 38.90563005, 39.16456385, 37.61570576,
       47.89553312, 55.58278162, 50.25443858, 41.32922291, 46.43412264,
       12.42807191, 13.21142306, 34.24427071, 33.02613312, 29.6548499 ,
       38.65740343, 48.50217647, 45.93325924, 36.47783608, 43.75498144,
       32.66721136, 46.22385176, 32.90933508, 39.07058013, 42.97524454,
       22.86746081, 43.54719163, 50.96817779, 47.22777093, 44.10958609,
       33.63211714, 16.21743988, 46.06934222, 42.44300417, 29.6548499 ,
       30.60622834, 35.47121623, 36.2590306 , 27.69005982, 32.67777571,
       52.86141141, 39.06948838, 34.37579118, 31.52751868, 34.36432665,
       46.27911303, 36.00559827, 41.08312589, 24.12622065, 47.11778643,
       33.60606062, 46.04003399, 40.81173845, 31.54922966, 50.96817779,
       48.15212042, 35.44452254,  9.86432876, 40.056905  , 38.85224267,
       37.73108279, 34.14110402, 32.74970038, 43.43306115, 47.94614374,
       33.83137443, 15.44332295, 35.6672742 , 47.46830657, 44.943128  ,
       48.40875175, 28.24791648, 22.28034944, 45.98664661, 39.40299593,
       47.94614374, 50.23810341, 32.90862227, 28.32799754, 43.79472624,
       50.96817779, 52.83471772, 30.68342502, 30.96894251, 34.32435177,
       29.8790501 , 38.67841352, 12.91176579, 15.76500852, 42.10774072,
       41.23199898, 40.84768001, 25.52059561, 15.08843212, 27.9668724 ,
       43.32611713, 47.66586849, 29.12285317, 44.84002526, 45.16364101,
       24.23305642, 48.94701568, 40.50274154, 46.48379248, 47.52169394,
       26.31172454, 46.56042875, 34.14482563, 34.3808308 , 44.96989594,
       38.15787243, 34.22715201, 15.55561773, 43.37967378, 41.75616328,
       30.45102191, 44.99480217, 46.61381613, 12.43462648, 35.21537502,
       40.04491175, 42.78961187, 14.6824248 , 42.55710308, 10.19892774,
       35.44452254, 44.00684329, 46.04003399, 44.00684329, 31.49505075,
       44.08692436, 45.32100944, 42.55710308, 48.40875175, 50.96817779,
       39.07058013, 46.83277307, 36.4055003 , 46.50704138, 44.93951755,
       44.91282386, 41.34271413, 39.67088304, 39.89515302, 35.94148676,
       48.2811239 , 54.24833284, 41.62307384, 26.202338  , 44.92693027,
       42.63718414, 46.23791957, 38.22012962, 32.16072916, 41.75363631,
       15.30985452, 45.93325924, 53.57065221, 39.87088321, 32.80694862,
       40.80228005, 30.86460863, 49.23498511, 30.72801085, 52.84096768,
       46.6483485 , 30.93111145, 47.12998886, 37.24599645, 37.62987634,
       45.93526244, 52.80802404, 41.37307946, 40.46763404, 42.78572412,
       46.05257504, 39.81706067, 40.00399496, 43.66659802, 43.43306115,
       33.2723514 , 34.69116796, 35.41128566, 33.63211714, 51.12774401,
       41.20135547, 46.61381613, 47.86362348, 47.45382204, 28.69915596,
       36.42732444, 52.75463666, 15.73831483, 40.00843326, 33.72503375,
       30.74811456, 44.943128  , 34.29765809, 28.17530609, 39.69845723,
       22.96315606, 43.48782377, 39.14571509, 15.08843212, 36.15225586,
       52.75463666])

In [26]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [27]:
r2_score(y_train,y_pred_train)

0.5621358579203621

In [28]:
mean_absolute_error(y_train,y_pred_train)

6.247712847534594

## Predict on Test Data

In [29]:
y_pred_test = lr.predict(X_test)

In [30]:
r2_score(y_test,y_pred_test)

0.6612461467162026

In [31]:
mean_absolute_error(y_test,y_pred_test)

5.669976596012609